// <auto-generated />
using System;
using FilaDeCampo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FilaDeCampo.Migrations
{
    [DbContext(typeof(DbSolaresCampo))]
    partial class DbSolaresCampoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilaDeCampo.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CongregacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UltimoDirigenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("FilaDeCampo.Models.Congregacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Congregacoes");
                });

            modelBuilder.Entity("FilaDeCampo.Models.Dirigente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CongregacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdemRodizio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.ToTable("Dirigentes");
                });

            modelBuilder.Entity("FilaDeCampo.Models.EscalaDeSabado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CongregacaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DirigenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CongregacaoId");

                    b.HasIndex("DirigenteId");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("FilaDeCampo.Models.Configuracao", b =>
                {
                    b.HasOne("FilaDeCampo.Models.Congregacao", "Congregacao")
                        .WithMany()
                        .HasForeignKey("CongregacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congregacao");
                });

            modelBuilder.Entity("FilaDeCampo.Models.Dirigente", b =>
                {
                    b.HasOne("FilaDeCampo.Models.Congregacao", "Congregacao")
                        .WithMany("Dirigentes")
                        .HasForeignKey("CongregacaoId");

                    b.Navigation("Congregacao");
                });

            modelBuilder.Entity("FilaDeCampo.Models.EscalaDeSabado", b =>
                {
                    b.HasOne("FilaDeCampo.Models.Congregacao", "Congregacao")
                        .WithMany()
                        .HasForeignKey("CongregacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilaDeCampo.Models.Dirigente", "Dirigente")
                        .WithMany()
                        .HasForeignKey("DirigenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congregacao");

                    b.Navigation("Dirigente");
                });

            modelBuilder.Entity("FilaDeCampo.Models.Congregacao", b =>
                {
                    b.Navigation("Dirigentes");
                });
#pragma warning restore 612, 618
        }
    }
}
